server:
  port: 80
spring:
  application:
    name: config-client
  cloud:
    config:
#      分支名称
      label: master
      #      配置文件名称
      name: config
      profile: test
      #      配置中心地址
      uri: http://localhost:8088
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
  # rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"