server:
  port: 8093
spring:
  application:
    name: seata-account
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8488
    alibaba:
      seata:
        tx-service-group: tx_group
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: account
    password: jrealsoft
    