server:
  port: 9001

eureka:
  instance:
#    appname: eurekaclient
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server-8001:8001/eureka/,http://eureka-server-8002:8002/eureka/
spring:
  application:
    name: eureka-client
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@116.55.251.208:1251:dev
    username: jres
    password: jrealsoft
    type: com.alibaba.druid.pool.DruidDataSource
