server:
  port: 80
spring:
  application:
    name: zookeeper-consumer
  cloud:
    zookeeper:
      connect-string: localhost:2181
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: job
    password: test
    type: com.alibaba.druid.pool.DruidDataSource