server:
  port: 8002

eureka:
  instance:
    hostname: server8002
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka-server-8001:8001/eureka/
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@116.55.251.208:1251:dev
    username: jres
    password: jrealsoft
    type: com.alibaba.druid.pool.DruidDataSource
