server:
  port: 8089
spring:
  application:
    name: cofig-client8089
  cloud:
    config:
      uri: http://localhost:8088
      #      配置文件名称
      name: config
      profile: test
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
  # rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"