server:
  port: 8081
spring:
  application:
    name: hystrix-client
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka