server:
  port: 8001

eureka:
  instance:
    #eureka-server-8001
    hostname: server8001
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://eureka-server-8002:8002/eureka/
  server:
    enable-self-preservation: false
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: job
    password: test
    type: com.alibaba.druid.pool.DruidDataSource
  sleuth:
    sampler:
      probability: 1

management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
    loggers:
      enabled: true